services:
  app:
    build: .
    ports:
      - "8080:8080"

  jmeter:
    build: ./jmeter
    profiles: ["prueba"]
    volumes:
      - ./jmeter:/tests
      - ./resultados:/resultados
    environment:
      JMETER_ARGS_EXTRA: "-Jhost=app"
    depends_on:
      - app