apiVersion: 1

datasources:
  - name: InfluxDB-JMeter
    uid: influxdb-jmeter
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      dbName: jmeter
      httpMode: GET
    isDefault: true

  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
