apiVersion: 1

datasources:
  - name: InfluxDB-JMeter
    uid: influxdb-jmeter
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      dbName: jmeter
      httpMode: GET
      timeInterval: 5s
    isDefault: false

  - name: Prometheus
    uid: prometheus-lab
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    jsonData:
      timeInterval: 5s
    isDefault: true
